### ISSUE TITLE
Setting SHELL to cmd in Makefile is not portable

### ISSUE THREAD

**Issue by kyak** [RC-MODULE/nmpp#40]
This line here:
https://github.com/RC-MODULE/nmpp/blob/66760c4a3e8164bef0783bef4ab776c0bb589750/make/nmpp-nmc3/Makefile#L48
will not work on Linux hosts.

Maybe you should use $(shell) built-in?

**Comment by kyak** [comment]
В файле make/nmpp-nmc3/Makefile есть строка "SHELL = cmd". При сборке на Linux это приводит к ошибке:

gmake: cmd: Command not found
gmake: *** [default] Error 127

Есть просто убрать эту строчку, то на Linux всё работает. На Windows это не приводит к проблемам, всё продолжает работать.

**Comment by sergnmc** [comment]
fixed
