### ISSUE TITLE
fft2.h doesn't exist anymore

### ISSUE THREAD

**Issue by kyak** [RC-MODULE/nmpp#41]
fft2.h file doesn't exist anymore, compilation breaks:

https://github.com/RC-MODULE/nmpp/blob/e18d1621d5bee3a053d638cacdd36996605827a3/app/examples/rpc/fft-1024/arm/main-arm.c#L5

**Comment by kyak** [comment]
Файла fft2.h больше нет, однако на него есть отсылки, например, отсюда (и из других мест тоже): app/examples/rpc/fft-1024/arm/main-arm.c. У себя я просто поменял include "fft2.h" на include "fft.h", всё работает.

**Comment by sergnmc** [comment]
fixed
