### ISSUE TITLE
Building host library in Visual 2017 x64

### ISSUE THREAD

**Issue by kyak** [RC-MODULE/nmpp#45]
Чтобы заработала сборка хостовой библиотеки в Visual Studio 2017. В make\nmpp-x86-x64\Makefile новые секции:

VS15X64   = Visual_Studio_15_2017_Win64

configure-vs15x64         $(VS15X64)/nmpp-x64.vcxproj:
    -$(RMDIR)   $(VS15X64)
    $(MKDIR)     $(VS15X64)
    cd           $(VS15X64) &&    cmake .. -G  "Visual Studio 15 2017 Win64"

vs15x64:        $(VS15X64)/nmpp-x64.vcxproj
    cd            $(VS15X64) && "$(VS150COMNTOOLS)VsDevCmd" && msbuild nmpp-x64.vcxproj
    cd            $(VS15X64) && "$(VS150COMNTOOLS)VsDevCmd" && msbuild nmpp-x64.vcxproj /p:Configuration=Release

**Comment by sergnmc** [comment]
fixed by target
make vs2017
