### ISSUE TITLE
Switch to UTF-8 in source files

### ISSUE THREAD

**Issue by a1batross** [RC-MODULE/nmpp#49]
Some files using CP1251 encoding which makes them unreadable through GitHub or in any text editor that doesn't recognize encodings. How about switching them to UTF-8? It's supported mostly everywhere now.

I will send a patch shortly re-encoding all text files.

**Comment by nekromant** [comment]
@sergnmc Это к тебе

**Comment by mosolovsa** [comment]
http://rc-module.github.io/nmpp/index.html
![image](https://user-images.githubusercontent.com/15525120/186892340-f8f6574e-43b4-4de4-92d7-5a1870f4b67a.png)
